maintainer: Dhanoop Karunakaran
debug: False
train:
  lr: 0.0001
  gamma: 0.99
  betas:
    - 0.9
    - 0.999
  random_seed: 543
  n_epidode: 1200
  batch_size: 32
  update_freq: 64 #every 4 step_dones
  target_update_freq: 10 #every 10 episodes.
  store_stats: 50 # every 50 episodes
  epsilon: 0.99
  stats:
      loss: []
      avg_loss: []
replay_buffer_size: 10000

