maintainer: Dhanoop Karunakaran
debug: True
train:
  lr: 0.0001
  gamma: 0.99
  betas:
    - 0.9
    - 0.999
  random_seed: 543
  n_epidode: 5000
  n_timesteps: 10
  batch_size: 32
  update_freq: 64 #every 4 iteration
  target_update_freq: 1000 #every 10 iteration.
  epsilon_start: 0.9
  epsilon_end: 0.05
  epsilon_decay: 1000
replay_buffer_size: 10000

